### ISSUE TITLE
Why serializeHasMany is turned off by default?

### ISSUE THREAD

**Issue by firstsano** [adopted-ember-addons/active-model-adapter#116]
I wonder why serialization of hasMany relationships is turned off by default, and why there's no mention about it in docs. It looks like bug until you discover comment in source code. Are there any performance reasons?

**Comment by DuBistKomisch** [comment]
I agree, this is my workaround:
```
import DS from 'ember-data';
import { ActiveModelSerializer } from 'active-model-adapter';

export default ActiveModelSerializer.extend({
 serializeHasMany() {
   return DS.JSONSerializer.prototype.serializeHasMany.apply(this, arguments);
 }
});
```
