### ISSUE TITLE
Moving Forward

### ISSUE THREAD

**Issue by jherdman** [adopted-ember-addons/active-model-adapter#119]
Hey friends.

I wanted to bump ember-inflector this morning, but noticed this addon is quite dated. Before I go with a heavy handed PR to update numerous dependencies I wanted to check what the safe pathway forward is here. Some questions:

- [x] Do we care about pre-3 Ember/Data?
- [x] Do we care about Bower?
- [x] Do we care about Ruby Gems?

**Comment by runspired** [comment]
We do not care about pre-3 or bower.  I am not qualified to answer the question on Ruby gems.

**Comment by jherdman** [comment]
I think I'm willing to try and take on upgrading this project's various dependencies. I have a fairly heavy handed approach in mind which is as follows:

1. Generate an entirely new addon in a new directory
2. Copy over pertinent files
3. Iterate until green
4. Copy back files into a clone of the project in a feature branch
5. Let Git do its magic

I think this will work, though it'll result in one ugly PR. Thoughts?

**Comment by dcyriller** [comment]
> Do we care about Ruby Gems?

I am even less qualified to answer.

But I'm just seeing that issue issue now. 😄 And I opened some time ago https://github.com/ember-data/active-model-adapter/pull/130. I was proposing there to set the ruby gem under maintenance mode. If the PR is accepted, it could be possible to cut a v3 release. The suppport for the gem would be (theorically) done on v2.

It could be an intermediate step to what you propose @jherdman.

**Comment by jherdman** [comment]
I wanted to raise this again. It's been a while, there seems to be no traction. This addon is an integral part of our various apps, and we want to help. Could we get a little guidance and help on how to move this forward? I'm more than willing to help out.

**Comment by jherdman** [comment]
@runspired I'm sorry pester on this, but is there any way this could be raised with ember-data core? If there's just no time from the core team perhaps we could make this an adopted addon?

**Comment by runspired** [comment]
apologies I'm not actively developing on anything these days. I think this should probably move to `adopted ember addons` and whatever direction you all take be up to you all. @igorT thoughts?

**Comment by jherdman** [comment]
@igorT have you had time to give this some thought?

**Comment by rreckonerr** [comment]
Would be awesome to see this addon maintained!

**Comment by jherdman** [comment]
Ping @igorT  — sorry to nag. Gotta strike while the iron is hot.

**Comment by igorT** [comment]
@jherdman thank you for the repeated pings, it has been true that we hadn't had time to devote to this addon. I am supportive of releasing to adopted addon's, I'll bring this up in the next wednesdays data meeting. In the meantime @jherdman can you take https://github.com/ember-data/active-model-adapter/pull/121 over and open a new PR and clean it up? It wasn't very far from being ready to merge.

**Comment by jherdman** [comment]
Sure thing! Apologies for the... uh... harassment 😁 I'm just eager!

**Comment by runspired** [comment]
We discussed moving this to adopted-ember-addons in our team meeting today and everyone agrees, have reached out to initiate that process.

**Comment by jherdman** [comment]
🕺🏻

**Comment by jherdman** [comment]
@runspired any idea who'll be left as maintainers so that I can converse with them over the #139 PR?

**Comment by runspired** [comment]
Myself and Igor will remain for now, but I've recommended you be added. If you're not on discord I recommend joining and reaching out to @MelSumner in the adopted-ember-addons channel to get set up. Adopted addons have their own policy regarding maintainers that is lenient and straightforward for folks who want to do work ♥️. You can read about it here: https://github.com/adopted-ember-addons/program-guidelines
