### ISSUE TITLE
[QUEST] v3

### ISSUE THREAD

**Issue by jherdman** [adopted-ember-addons/active-model-adapter#153]
- [x] #152 
- [x] #151 
- [x] #147 
- [x] #150 
- [x] #149

**Comment by jherdman** [comment]
@MelSumner I'm unable to cut a release at this time. Should you be doing it still?

**Comment by jherdman** [comment]
Ping @MelSumner. Should I be granted access to cut a release is there documentation on how best to do this outside of the release-it scripts? E.g. should I do the publish from my branch, or the upstream?

**Comment by gilest** [comment]
Looks like you can close this ;)

**Comment by jherdman** [comment]
Indeed I can! 🥳
