### ISSUE TITLE
Possible regression bug with side-loaded hasMany 

### ISSUE THREAD

**Issue by david-casagrande** [adopted-ember-addons/active-model-adapter#26]
see http://emberjs.jsbin.com/foyuza for example.

where `model:stream` has a `hasMany` relationship to `model:activity` which has a `belongsTo` relationship to `model:stream.` when fetching a single `model:stream` record with side-loaded activities (which reference a different stream) the  `hasMany` relationship breaks down, as shown in the example. This can be fixed by specifying `inverse: null` on either `model:stream` or `model:activity` 

i listed this a a 'possible' regression because while this worked in beta.19 it could  have been a bug and the behavior im seeing now is correct. 

i also realize this might be am `ember-data` issue and not relevant to `active-model-adapter` but figured i'd start here.

**Comment by jherdman** [comment]
Hi @david-casagrande is this still an issue?
