### ISSUE TITLE
[enhancement] Improve warning when not using the active_model_serializers gem

### ISSUE THREAD

**Issue by noise-machines** [adopted-ember-addons/active-model-adapter#33]
When you haven't configured your Rails back-end to use active_model_serializers, you get this message:

`WARNING: Encountered "0" in payload, but no model was found for model name "0"`

I'm not sure if this warning is coming from active-model-adapter, or elsewhere in Ember Data, but it would be nice to add a potential solution. Something like:

`WARNING: Encountered "0" in payload, but no model was found for model name "0". Is Rails properly configured to use the active_model_serializers gem?`

I don't think that's exactly the right message, but you get the idea.

P.S.: Thanks for the great work you guys are putting in on Ember. :)

**Comment by fivetanley** [comment]
What this means is that you have an array whereas the AMS expects a json object as the top level object. The messaging should be improved though.

**Comment by jherdman** [comment]
@noise-machines is this still an issue for you?
