### ISSUE TITLE
AMA Errors Not Working

### ISSUE THREAD

**Issue by ghost** [adopted-ember-addons/active-model-adapter#45]
Hey!

I followed the instructions given here: http://emberjs.com/api/data/classes/DS.Errors.html but it doesnt seem to work.

My API is returning JSON that looks like this:

``` json
{
    "errors": {
        "email": ["The email address is already being used."]
    }
}
```

and then in my template I put:

``` hbs
{{#each model.errors.messages as |message|}}
  <div class="error">
    {{message}}
  </div>
{{/each}}
```

This is the code I am using to update the user:

``` js
export default Ember.Controller.extend({
  actions: {
    updateUser(model) {
      this.set('loading', true);
      model.get('content').save().then(()=> {
        Materialize.toast('Your information has been updated.', 5000);
      }).catch(() => {
        Materialize.toast('There was a problem updating your information.', 5000);
      }).finally(() => {
        this.set('loading', false);
      });
    }
  }
});
```

Its not working (no errors are showing up on the screen). I verified that im using AMA.

Any ideas/suggestions?

Thanks.

**Comment by mjanda** [comment]
By any chance, are you using ember-validations? They break server-side validation.

**Comment by nahtnam** [comment]
No, I'm not using ember-validations.

**Comment by JKGisMe** [comment]
I have the same problem. If it works a different way perhaps it can be added to the readme or something?

**Comment by tcjr** [comment]
Any update on this, @nahtnam?  Do you have a work-around?

**Comment by fivetanley** [comment]
What happens if you do `models.errors.email` ?

**Comment by fivetanley** [comment]
Ah I see you want the special list of messages. brb checking more into this.

**Comment by nahtnam** [comment]
@tcjr No, I didn't find one. I am actually redoing my app so it might be a while until I get to authentication again.

@fivetanley I also tried `model.errors.email` and it didn't work.

**Comment by fivetanley** [comment]
What version of Ember Data are you using as well?

**Comment by nahtnam** [comment]
I think 1.13.10 or something. My new app is running 2.0 though.

**Comment by fivetanley** [comment]
I tried to create a test here. https://github.com/ember-data/active-model-adapter/pull/51 I am having trouble reproducing.

**Comment by nahtnam** [comment]
Sorry for the late reply. I just finished re-doing my app. I will try once again.

Should I model my json like this? 

```
errors: {
  name: ['rejected'],
  genre: ['rejected']
}
```

and return a 402 status code?

What should the hbs look like?

Thanks.

**Comment by mjanda** [comment]
I think you should return 422 response.

**Comment by nahtnam** [comment]
Whoops, typo. You're right.

**Comment by nahtnam** [comment]
The tests make use of only `.save()`. What about get/find/findAll?

**Comment by nahtnam** [comment]
New discovery @fivetanley. I keep getting this second error that says the adapter rejected the commit.

http://i.imgur.com/xnexb9d.png

The json im returning is:
```
{
  "errors": {
    "game": [
      "This user does not own Counter-Strike: Global Offensive."
    ]
  }
}
```

and the status is `422`.

Thanks.

**Comment by nahtnam** [comment]
Bump. Still having this issue.

**Comment by pangratz** [comment]
Hey @nahtnam, I *think* I can reproduce the issue that no errors are shown in the UI: http://ember-twiddle.com/74bdbdcfa9e59790103a. Can you check if the `status` of your response is the string `"422"`? Because if it is a string, then the error returned by the adapter is not an `InvalidError` but an `AdapterError`, which doesn't have the error messages.

Can you confirm that this is in fact the case in your issue? Can you change `status` to be `422` and check if that solves your issue?

**Comment by nahtnam** [comment]
?

According to postman, im properly returning 422.

![http://i.imgur.com/S3D8DhO.png](http://i.imgur.com/S3D8DhO.png)

**Comment by pangratz** [comment]
Yep. It would have been weird if the status was a string anyway.

Did you take a look at the twiddle? Can you spot any differences to your situation? Especially regarding the used versions?

**Comment by nahtnam** [comment]
Two differences that I see.

1. Im not using the Active Model Serializer. I only have the Active Model Adapter installed
2. Right now, im not using `.save()`, but instead im passing the error when `return this.store.findRecord('user', 1);` fails (in my case, if the user doesnt own the game).

Are either of those important?

**Comment by pangratz** [comment]
> Im not using the Active Model Serializer. I only have the Active Model Adapter installed

The Active Model Serializer should be used automatically when the Active Model Adapter is used. Can you check if this is the case though by reporting back the output of `this.store.serializerFor('user').toString()`, just before you find the user record?

---

Also, what versions of ember and ember-data are you using? The versions are printed in the console at the top when you reload your app. It looks something like this:

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.0.1
DEBUG: Ember Data : 2.0.1
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

If you don't see this, you can get the versions via:

```
console.log(Ember.VERSION);
console.log(DS.VERSION);
```

---

> Right now, im not using .save(), but instead im passing the error when return this.store.findRecord('user', 1); fails (in my case, if the user doesnt own the game).

I might be wrong but it is not possible to specify a validation error when finding a record. Can you post a JSBin / Ember-Twiddle with what your current approach is?

**Comment by mmahalwy** [comment]
Anything on this? I am getting the same problem too

**Comment by pangratz** [comment]
@mmahalwy can you provide some code, demonstrating the issue? This would greatly help tracking down the issue. You can use [this ember-twiddle](https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8/copy?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) as a starting point.

**Comment by jherdman** [comment]
@mmahalwy is this still an issue for you?
