### ISSUE TITLE
Facing an issue when adding relationships in Ember 2.12

### ISSUE THREAD

**Issue by GauravShetty1016** [adopted-ember-addons/active-model-adapter#95]
When I have relationships in my models I face this error:
Assertion Failed: You can no longer pass a modelClass as the first argument to store.buildInternalModel. Pass modelName instead.

The error originates in the method: setupRelationships
The normal RESTAdapter works with no issues.

My model is defined as so:
export default DS.Model.extend({
  name: DS.attr(),
  email: DS.attr(),
  profilePic: DS.attr(),
  userProfiles: DS.hasMany()
});

I have tried:
userProfiles: DS.hasMany('userProfile')
userProfiles: DS.hasMany('user-profile')

**Comment by benmurden** [comment]
From what I can tell from stack traces, payloads that are pushed into the store must now have a `type` property on them.

e.g.
```json
{
  id: 1,
  type: "post",
  title: "It really is a post"
}
```
